NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/sub.orderer.dev.be-ys-research.fr-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/sub.orderer.dev.be-ys-research.fr-cert.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/sub.orderer.dev.be-ys-research.fr-cert.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/sub.orderer.dev.be-ys-research.fr-cert.pem
    OrganizationalUnitIdentifier: orderer
