# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Org0
    Domain: sub0.dev.be-ys-research.fr
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 1