# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: sub1.dev.be-ys-research.fr
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1